name: Bug Report
description: "Report something that's broken."
body:
  - type: input
    attributes:
      label: Livewire Version
      placeholder: "#.#.#"
    validations:
      required: true
  - type: input
    attributes:
      label: Livewire Flux Version
      placeholder: "#.#.#"
    validations:
      required: false
  - type: input
    attributes:
      label: Laravel Version
      placeholder: "#.#.#"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true