name: Bug Report
description: "Report something that's broken."
body:
  - type: markdown
    attributes:
      value: "Please read ."
  - type: input
    attributes:
      label: Laravel Version
      description: Provide the Laravel version that you are using. [Please ensure it is still supported.](https://laravel.com/docs/releases#support-policy)
      placeholder: 10.4.1
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: Provide the PHP version that you are using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: input
    attributes:
      label: Livewire Version
      description: If applicable, provide the database driver and version you are using.
      placeholder: "MySQL 8.0.31 for macOS 13.0 on arm64 (Homebrew)"
    validations:
      required: false
  - type: input
    attributes:
      label: Livewire Flux Version
      description: If applicable, provide the database driver and version you are using.
      placeholder: "MySQL 8.0.31 for macOS 13.0 on arm64 (Homebrew)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true